language: node_js
matrix:
  fast_finish: true
  include:
    - node_js: "0.12"
    - node_js: "0.11"
    - node_js: "0.10"
    - node_js: "iojs"
addons:
  apt_packages:
    - libclamav-dev
before_script:
  - echo "DatabaseMirror database.clamav.net" >> freshclam.conf
  - freshclam --config-file freshclam.conf
