language: node_js
matrix:
  fast_finish: true
  include:
    - node_js: "0.12"
    - node_js: "0.11"
    - node_js: "0.10"
    - node_js: "iojs"
addons:
  apt_packages:
    - libclamav-dev
before_script:
  - sudo mkdir /var/lib/clamav && sudo chmod 777 /var/lib/clamav
  - wget http://db.local.clamav.net/main.cvd -O /var/lib/clamav/main.cvd
  - wget http://db.local.clamav.net/daily.cvd -O /var/lib/clamav/daily.cvd
